const C = {
	DEBUG: false,
	DEFAULT_LOCALE: 'en',
	TRANSITION_SPEED: 200,
	ONE_DAY_IN_SECONDS: 24 * 60 * 60,

	PANELS: {
		OVERVIEW: 'overview',
		LOCATIONS: 'locations',
		SPECIES: 'species'
	},
	CORE: {
		APP_VERSION: "2.0.0 - BETA",
		RELEASE_DATE: "Jan 17, 2015",
		GITHUB_URL: "https://github.com/benkeen/birdsearch.org"
	},
	SEARCH_SETTINGS: {
		DEFAULT_SEARCH_DAYS: 30,
		NUM_SEARCH_DAYS: 30
	},

	PANEL_DIMENSIONS: {
		PADDING: 0,
		TOP: 60,
		OVERVIEW_PANEL_HEIGHT: 106,
		LEFT_PANEL_WIDTH: 300,
		LEFT_PANEL_FOOTER_HEIGHT: 24
	},

	COLOUR_RANGES: {
		RANGE1: 10,
		RANGE2: 20,
		RANGE3: 30,
		RANGE4: 40,
		RANGE5: 50,
		RANGE6: 60,
		RANGE7: 70,
		RANGE8: 80
	},

	LOCATION_SORT: {
		FIELDS: {
			LOCATION: 'LOCATION_SORT_LOCATION',
			SPECIES: 'LOCATION_SORT_SPECIES'
		},
		DIR: {
			DEFAULT: 'LOCATION_SORT_DIR_DEFAULT',
			REVERSE: 'LOCATION_SORT_DIR_REVERSE'
		}
	}

};

export { C };
