const E = {
  SELECT_TAB: 'SELECT_TAB',
  SET_LOCALE: 'SET_LOCALE',
  SET_INTRO_OVERLAY_VISIBILITY: 'SET_INTRO_OVERLAY_VISIBILITY',
  SET_ADVANCED_SEARCH_VISIBILITY: 'SET_ADVANCED_SEARCH_VISIBILITY',
  REQUESTING_USER_LOCATION: 'REQUESTING_USER_LOCATION',
  RECEIVED_USER_LOCATION: 'RECEIVED_USER_LOCATION',
  SET_SEARCH_LOCATION: 'SET_SEARCH_LOCATION',
  SEARCH_REQUEST_STARTED: 'SEARCH_REQUEST_STARTED',
  SEARCH_REQUEST_ENDED: 'SEARCH_REQUEST_ENDED',
  TOGGLE_PANEL_VISIBILITY: 'TOGGLE_PANEL_VISIBILITY',
  SEARCH_LOCATIONS_RETURNED: 'SEARCH_LOCATIONS_RETURNED',
  VISIBLE_LOCATIONS_UPDATED: 'VISIBLE_LOCATIONS_UPDATED',
  HOTSPOT_SIGHTINGS_RETURNED: 'HOTSPOT_SIGHTINGS_RETURNED',
  WINDOW_RESIZED: 'WINDOW_RESIZED'
};

export { E };
